<a href="https://colab.research.google.com/github/blueberrylazjy/pytorch/blob/main/Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

x = torch.ones(2,3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [2]:
y = x+2
print(y)
print(y.grad_fn)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y*3
print(z)

out = z.mean()
print(out)

tensor([[9., 9., 9.],
        [9., 9., 9.]], grad_fn=<MulBackward0>)
tensor(9., grad_fn=<MeanBackward0>)


In [6]:
a = torch.tensor([1.0], requires_grad=True)
b= a*2
b.backward()
print(a.grad)

tensor([2.])


In [18]:
def calc(a):
  b=a*2 +1
  print(b)
  c=b*b
  print(c)
  d=c/(c+2)
  print(d)
  e=d.mean()
  print(e)
  return e

x=[1.0, 2.0, 3.0]
x=torch.tensor(x, requires_grad=True)
y= calc(x)
y.backward()
print(x.grad)

tensor([3., 5., 7.], grad_fn=<AddBackward0>)
tensor([ 9., 25., 49.], grad_fn=<MulBackward0>)
tensor([0.8182, 0.9259, 0.9608], grad_fn=<DivBackward0>)
tensor(0.9016, grad_fn=<MeanBackward0>)
tensor([0.0661, 0.0183, 0.0072])


In [17]:
delta=0.001
x=[1.0, 2.0, 3.0]
x=torch.tensor(x)
y=calc(x)
print(y)
x_1=[1.0+delta, 2.0, 3.0]
x_1=torch.tensor(x_1)
y_1=calc(x_1)
x_2=[1.0, 2.0+delta, 3.0]
x_2=torch.tensor(x_2)
y_2=calc(x_2)
x_3=[1.0, 2.0, 3.0+delta]
x_3=torch.tensor(x_3)
y_3=calc(x_3)
print(y_1)
grad_1=(y_1-y)/delta
print(grad_1)
grad_2=(y_2-y)/delta
print(grad_2)
grad_3=(y_3-y)/delta

grads=torch.stack((grad_1, grad_2, grad_3))
# Tensorを統合
print(grads)

tensor(0.9016)
tensor(0.9017)
tensor(0.0660)
tensor(0.0183)
tensor([0.0660, 0.0183, 0.0072])
